/* eslint-disable quotes */
import {
  AI_AUTO_GENERATED_FIELDS_DEFAULT,
  parseAiAutoGeneratedFieldsString,
  parseTitleAndCaption,
} from "@/photo/ai";
import { parsePromptJsonResponse } from "@/platforms/cloudbase-ai";
import { z } from "zod";

const objectSchema = z.object({
  title: z.string(),
  tags: z.array(z.string()),
});

describe('AI parses', () => {
  describe('prompt-JSON responses (CloudBase AI fallback)', () => {
    it('from raw JSON', () => {
      expect(parsePromptJsonResponse(
        '{"title":"Sunset","tags":["dusk"]}',
        objectSchema,
      )).toStrictEqual({ title: 'Sunset', tags: ['dusk'] });
    });
    it('from markdown-fenced JSON', () => {
      expect(parsePromptJsonResponse(
        '```json\n{"title":"Sunset","tags":[]}\n```',
        objectSchema,
      )).toStrictEqual({ title: 'Sunset', tags: [] });
      expect(parsePromptJsonResponse(
        '```\n{"title":"Sunset","tags":[]}\n```',
        objectSchema,
      )).toStrictEqual({ title: 'Sunset', tags: [] });
    });
    it('throwing on non-JSON output', () => {
      expect(() => parsePromptJsonResponse(
        'The image shows a sunset.',
        objectSchema,
      )).toThrow('non-JSON');
    });
    it('throwing on schema violations', () => {
      expect(() => parsePromptJsonResponse(
        '{"title":"Sunset","tags":"dusk"}',
        objectSchema,
      )).toThrow('schema validation');
      expect(() => parsePromptJsonResponse(
        '{"tags":[]}',
        objectSchema,
      )).toThrow('schema validation');
    });
  });
  describe('auto-generated fields', () => {
    it('with spaces', () => {
      expect(parseAiAutoGeneratedFieldsString())
        .toStrictEqual(AI_AUTO_GENERATED_FIELDS_DEFAULT);
      expect(parseAiAutoGeneratedFieldsString('all'))
        .toStrictEqual(['title', 'caption', 'tags', 'semantic']);
      expect(parseAiAutoGeneratedFieldsString('title'))
        .toStrictEqual(['title']);
      expect(parseAiAutoGeneratedFieldsString('title, caption'))
        .toStrictEqual(['title', 'caption']);
      expect(parseAiAutoGeneratedFieldsString('title, caption, invalid'))
        .toStrictEqual(['title', 'caption']);
      expect(parseAiAutoGeneratedFieldsString('title, caption, invalid, tags'))
        .toStrictEqual(['title', 'caption', 'tags']);
      expect(parseAiAutoGeneratedFieldsString('none'))
        .toStrictEqual([]);
    });
    it('without spaces', () => {
      expect(parseAiAutoGeneratedFieldsString('title,caption'))
        .toStrictEqual(['title', 'caption']);
      expect(parseAiAutoGeneratedFieldsString('title,caption,invalid'))
        .toStrictEqual(['title', 'caption']);
      expect(parseAiAutoGeneratedFieldsString('title,caption,invalid,tags'))
        .toStrictEqual(['title', 'caption', 'tags']);
    });
  });
  it('received titles and captions', () => {
    // Complex case
    expect(parseTitleAndCaption(
      `'Title: "Ephemeral Beauty" Caption: "Roses bask in fleeting sunlight."'`,
    )).toStrictEqual({
      title: 'Ephemeral Beauty',
      caption: 'Roses bask in fleeting sunlight',
    });
    // Without surrounding single quotes
    expect(parseTitleAndCaption(
      `Title: "Ephemeral Beauty"  Caption: "Roses bask in fleeting sunlight."`,
    )).toStrictEqual({
      title: 'Ephemeral Beauty',
      caption: 'Roses bask in fleeting sunlight',
    });
    // Without trailing period
    expect(parseTitleAndCaption(
      `Title: "Ephemeral Beauty"  Caption: "Roses bask in fleeting sunlight"`,
    )).toStrictEqual({
      title: 'Ephemeral Beauty',
      caption: 'Roses bask in fleeting sunlight',
    });
    // Without and quotes
    expect(parseTitleAndCaption(
      `Title: Ephemeral Beauty  Caption: Roses bask in fleeting sunlight`,
    )).toStrictEqual({
      title: 'Ephemeral Beauty',
      caption: 'Roses bask in fleeting sunlight',
    });
    // With single space
    expect(parseTitleAndCaption(
      `Title: Ephemeral Beauty Caption: Roses bask in fleeting sunlight`,
    )).toStrictEqual({
      title: 'Ephemeral Beauty',
      caption: 'Roses bask in fleeting sunlight',
    });
  });
});
